### ISSUE TITLE
Add Dark theme to the entire website

### ISSUE THREAD

**Issue by eshan1925** [eshan1925/portfolio_frontend_react#1]
Try designing the website for a dark theme yourself...

Will tell you to change the colors once the implementation part is done.

Give the button to change the theme at the top right corner.
Or wherever you find suitable.

**Comment by Divine-offishal** [comment]
Hi...i want to work on this

**Comment by eshan1925** [comment]
Go ahead @Divine-offishal

**Comment by Divine-offishal** [comment]
Okay... Thank you

**Comment by Divine-offishal** [comment]
Hi... I was having a hard time installing the dependencies in my IDE. It seems react-scripts has some installation issues
